---
language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker build -t pcs .

script:
  - bash tests/test.sh

